### ISSUE TITLE
Module cannot be found

### ISSUE THREAD

**Issue by michelleoj** [nikolalsvk/pusher-js-mock#10]
Hi! I was trying to use your library and noticed that my compiler couldn't find the module. Then I ran the runkit test on it (https://npm.runkit.com/pusher-js-mock) and saw that it was getting the same error. Do you mind removing the use of es6 syntax for importing and exporting your files in your `src` directory and in your package.json put `src/pusher-js-mock.js` as the value for the `main` key? 

Please and thanks! 😄

**Comment by nikolalsvk** [comment]
Oh shoot, I was including classes in tests directly from files, not from index.js (which doesn't exist) :)

Thanks for pointing this out, I'll fix it!

**Comment by nikolalsvk** [comment]
I've release 0.1.2 version, it should be fixed there, can you check? https://www.npmjs.com/package/pusher-js-mock

**Comment by michelleoj** [comment]
Thanks so much!!
