### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by mrded** [nikolalsvk/pusher-js-mock#14]
If would be great if you can add a TypeScript support.

Till then, I have to use something like this:
```
// *.d.ts
declare module 'pusher-js-mock' {
  import Pusher from 'pusher-js';

  export const PusherMock: Pusher;
}
```

**Comment by nikolalsvk** [comment]
Hey @mrded, thanks for opening the issue! 

Makes sense, I will add it. Do you have an idea on how to do this maybe? I can also look it up on my own, just asking if you know a quick way to do this :)

**Comment by mrded** [comment]
The quickest way will be to declare types in `*.d.ts` file, as it's written [here](https://medium.com/cameron-nokes/the-30-second-guide-to-publishing-a-typescript-package-to-npm-89d93ff7bccd)

The best way would be to rewrite whole module in TS.

**Comment by mayteio** [comment]
Hey guys, I've been working on a relatively typed mock for pusher - https://github.com/mayteio/use-pusher/blob/master/src/mocks.ts though not 100% confident in my typescript. @mrded did you want to take a look at let me know if it works for you?

**Comment by nikolalsvk** [comment]
Hey folks, I just relesed a Typescript version of this package! Here it is https://www.npmjs.com/package/pusher-js-mock/v/0.2.1

Check it out and tell me if I did something wrong :)
