### ISSUE TITLE
Publish the lib to npm

### ISSUE THREAD

**Issue by letoss** [nikolalsvk/pusher-js-mock#3]
Hi.

Is there any chance to get this lib published to npm?

**Comment by nikolalsvk** [comment]
@letoss sure thing, I just need to finish it.

Can you explain your use case, where would you use it? :) It would really help me with putting the proper README and finishing it.

**Comment by letoss** [comment]
@nikolalsvk Hello, I never saw that you answered me. I'm so sorry.

I have Pusher integrated to my app, when I run my test suite, my app try to send things through Pusher. To use this library I need to have it on npm to be download since I can't download lib to the project source code.

Does it make sense for you?

**Comment by nikolalsvk** [comment]
@letoss it's fine, it happens to everybody.

It makes sense for me, I just need to ask you how are you using Pusher in your app. Are you defining it globally on the `window` object or you're using it as a module?

I'll try to release soon with detailed README!

**Comment by letoss** [comment]
Oh sorry, now I got your question.

I created a wrapper for Pusher, basically to add some easy way to connect through it, join, rejoin and disconnect.

So, I instantiate the wrapper when one part of my app starts. Some events of my app will trigger pusher events, but it's not defined globally at windows. Does that answer your question? I really use the 10% of pusher power, but it's enough so far. I'm sorry that I cannot share my code, it's a private repo.

**Comment by nikolalsvk** [comment]
Oh OK, I think I understand how you're using it.

Can I just ask you what are you using to test your code? Particularly, what do you use for stubbing and mocking objects?

**Comment by letoss** [comment]
Sure!

I'm using Marionette as a framework. For testing I'm using mocha and I had to use sinon too, so, for now, I did some workaround for pusher just doing _createStubInstance_ over the Pusher wrapper. With this I have the same interface with the wrapper but it won't make any request.

As test runner I'm using karma BTW.

**Comment by nikolalsvk** [comment]
@letoss Just released the package on NPM, let me know if you find it usefu https://www.npmjs.com/package/pusher-js-mock
