### ISSUE TITLE
Trigger is echoing events to the originator

### ISSUE THREAD

**Issue by erickponce** [nikolalsvk/pusher-js-mock#47]
Hello there! 😀

It seems the `trigger` method of the mocked channel is echoing the event to the originator.

According to the Pusher docs, it should not happen:
"Client events are not delivered to the originator of the event. For more information see Message Routing."

https://pusher.com/docs/channels/using_channels/events/#triggering-client-events

Thank you for this great lib! 👏🎉

**Comment by erickponce** [comment]
Hello again 👋,

After some investigation, I found the issue.

It's only happening when using `trigger` instead of `emit`, this happens because on file `src/proxy-presence-channel.ts` it's not proxying the `trigger` method making it call the original `emit`, not the proxy one.

I think it's a simple fix, I'll create a Pull request for it.

Thanks again for this package!

**Comment by erickponce** [comment]
One last detail,

I think tests `#trigger -> is an alias for emit` and `#trigger -> emits pusher:member_added manually` will have to be changed, because they shouldn't expect to self emit these events.

**Comment by nikolalsvk** [comment]
Thanks for the fix and figuring this out, @erickponce. Can you also fix the test and we can merge and release your PR? Thanks 🙇

**Comment by erickponce** [comment]
No problem @nikolalsvk, I think it's ready to be merged now. Let me know if it need anything else.
🚀
